### ISSUE TITLE
This package cannot be installed from pypi

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-backend#123]
Something about the way the documentation  is configured in `setup.py` prevents installing this package from pypi:

```
Collecting ce==1.2.0 (from -r requirements.txt (line 1))
  Downloading https://pypi.pacificclimate.org/packages/ce-1.2.0.tar.gz (609kB)
    100% |████████████████████████████████| 614kB 36.7MB/s 
    Complete output from command python setup.py egg_info:
    /local_temp/lzeman/pip-build-6icbxml4/ce/setup.py:8: UserWarning: Could not import sphinx. You won't be able to build the docs
      warn("Could not import sphinx. You won't be able to build the docs")
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/local_temp/lzeman/pip-build-6icbxml4/ce/setup.py", line 49, in <module>
        'build_sphinx': BuildDoc
    NameError: name 'BuildDoc' is not defined
```

**Comment by corviday** [comment]
Package cannot be installed from github with pip, either, unless `sphinx` is hand-installed first.

**Comment by corviday** [comment]
Package also needs `contexttimer` installed.
