### ISSUE TITLE
generate_climos fails on files with 360_day calendar

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/climate-explorer-backend#34]
Example: Processing `/storage/data/climate/CMIP5/output/NIMR-KMA/HadGEM2-AO/historical/day/atmos/day/r1i1p1/v20130422/tasmin/tasmin_day_HadGEM2-AO_historical_r1i1p1_18600101-20051230.nc`:

```2017-05-09 22:02:57 INFO: Processing: /local_temp/rglover/tasmin_day_HadGEM2-AO_historical_r1i1p1_18600101-20051230.nc
2017-05-09 22:02:58 INFO: Generating climo period 1961-01-01 to 1990-12-30
2017-05-09 22:02:58 INFO: Selecting temporal subset
2017-05-09 22:03:10 INFO: Forming climatological means
Traceback (most recent call last):
  File "generate_climos.py", line 372, in <module>
    main(args)
  File "generate_climos.py", line 356, in main
    convert_longitudes=args.convert_longitudes, split_vars=args.split_vars)
  File "generate_climos.py", line 179, in create_climo_files
    update_climo_time_meta(climo_means)
  File "generate_climos.py", line 314, in update_climo_time_meta
    climo_bnds_var[:] = date2num(climo_bounds, cf.time_var.units, cf.time_var.calendar)
  File "netCDF4/_netCDF4.pyx", line 5265, in netCDF4._netCDF4.date2num (netCDF4/_netCDF4.c:65355)
  File "netcdftime/_netcdftime.pyx", line 795, in netcdftime._netcdftime.utime.date2num (netcdftime/_netcdftime.c:14358)
ValueError: there are only 30 days in every month with the 360_day calendar
```

This occurs for all model output files under `/storage/data/climate/CMIP5/output/NIMR-KMA/` and `/storage/data/climate/CMIP5/output/MOHC/`.

**Comment by rod-glover** [comment]
Problem is in climo_bounds calculation of annual mean end-date
